package wikidoc_test

import (
	"strings"
	"testing"

	"github.com/z-shell/zsh-lint/internal/wikidoc"
)

// TestSanitize_RemoveHTMLComment verifies that the gomarkdoc-generated header comment
// is stripped and surrounding content is preserved.
func TestSanitize_RemoveHTMLComment(t *testing.T) {
	input := "<!-- Code generated by gomarkdoc. DO NOT EDIT -->\n# Title"
	got := wikidoc.Sanitize(input)
	if strings.Contains(got, "<!--") {
		t.Errorf("Sanitize should remove HTML comments; got: %q", got)
	}
	if !strings.Contains(got, "# Title") {
		t.Errorf("Sanitize should preserve content after comment; got: %q", got)
	}
}

// TestSanitize_RemoveHTMLAnchor verifies that gomarkdoc anchor tags are removed.
func TestSanitize_RemoveHTMLAnchor(t *testing.T) {
	input := `<a name="Run"></a>

## func Run`
	got := wikidoc.Sanitize(input)
	if strings.Contains(got, "<a") {
		t.Errorf("Sanitize should remove HTML anchor tags; got: %q", got)
	}
	if !strings.Contains(got, "## func Run") {
		t.Errorf("Sanitize should preserve heading after anchor; got: %q", got)
	}
}

// TestSanitize_UnwrapAngleBracketLinks verifies angle-bracketed link destinations are unwrapped.
func TestSanitize_UnwrapAngleBracketLinks(t *testing.T) {
	cases := []struct {
		name  string
		input string
		want  string
	}{
		{
			name:  "fragment link",
			input: "[Run](<#Run>)",
			want:  "[Run](#Run)",
		},
		{
			name:  "full URL link",
			input: "[g](<https://h.example>)",
			want:  "[g](https://h.example)",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := wikidoc.Sanitize(tc.input)
			if got != tc.want {
				t.Errorf("Sanitize(%q) = %q; want %q", tc.input, got, tc.want)
			}
		})
	}
}

// TestSanitize_EscapeProseChars verifies bare < > { } are escaped on prose lines.
func TestSanitize_EscapeProseChars(t *testing.T) {
	input := "usage <file.zsh> {x}"
	got := wikidoc.Sanitize(input)
	want := "usage &lt;file.zsh&gt; &#123;x&#125;"
	if got != want {
		t.Errorf("Sanitize(%q) = %q; want %q", input, got, want)
	}
}

// TestSanitize_IndentedCodeNotEscaped verifies tab-indented code lines are left verbatim.
func TestSanitize_IndentedCodeNotEscaped(t *testing.T) {
	// A tab-indented code line — must NOT be escaped.
	input := "\tfunc F(a <T>) {}"
	got := wikidoc.Sanitize(input)
	if got != input {
		t.Errorf("Sanitize should not escape tab-indented code; got: %q, want: %q", got, input)
	}
}

// TestSanitize_FencedCodeNotEscaped verifies content inside fenced blocks is left verbatim.
func TestSanitize_FencedCodeNotEscaped(t *testing.T) {
	input := "```\n<y> {z}\n```"
	got := wikidoc.Sanitize(input)
	if got != input {
		t.Errorf("Sanitize should not escape fenced code block contents; got: %q, want: %q", got, input)
	}
}

// TestSanitize_FourSpaceIndentNotEscaped verifies 4-space-indented code lines are left verbatim.
func TestSanitize_FourSpaceIndentNotEscaped(t *testing.T) {
	input := "    func F(a <T>) {}"
	got := wikidoc.Sanitize(input)
	if got != input {
		t.Errorf("Sanitize should not escape 4-space-indented code; got: %q, want: %q", got, input)
	}
}
