---
name: Trunk Code Quality

on:
  push:
    branches: [main, next]
    tags: ["v*.*.*"]
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: "0 05 * * 5"
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Trunk Code Quality
    permissions:
      actions: read
      checks: write
      contents: read
    uses: z-shell/.github/.github/workflows/trunk.yml@98ec754f418f8d99e97b5ed532e0a1b1f94d96eb # main
    with:
      arguments: --no-progress
