---
name: Zsh Syntax Check
on:
  push:
    tags: ["v*.*.*"]
    branches:
      - main
      - next
    paths:
      - "**/*.zsh"
      - "legacy/functions/**"
      - ".github/workflows/zsh-n.yml"
  pull_request:
    paths:
      - "**/*.zsh"
      - "legacy/functions/**"
      - ".github/workflows/zsh-n.yml"
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  zsh-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: "Set matrix output"
        id: set-matrix
        run: |
          MATRIX="$(find . -type d -name 'doc' -prune -o -type f \( -iname '*.zsh' -o -iname 'zsh-lint*' -o -iname '.zsh-lint*' -o -iname '@zsh-lint*' \) -print0 | jq -Rsc 'split("\u0000") | map(select(length > 0) | {"file": .}) | {"include": .}')"
          echo "MATRIX=${MATRIX}" >&2
          echo "matrix=${MATRIX}" >> "$GITHUB_OUTPUT"
  zsh-n:
    runs-on: ubuntu-latest
    needs: zsh-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.zsh-matrix.outputs.matrix) }}
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: "⚡ Install dependencies"
        run: sudo apt update && sudo apt-get install -y zsh && touch ~/.zshrc
      - name: "⚡ zsh -n: ${{ matrix.file }}"
        env:
          ZSH_FILE: ${{ matrix.file }}
        run: |
          zsh -n "${ZSH_FILE}"
      - name: "⚡ zcompile ${{ matrix.file }}"
        env:
          ZSH_FILE: ${{ matrix.file }}
        run: |
          zsh -fc 'zcompile -- "$1"' zsh "$ZSH_FILE"; rc=$?
          ls -al -- "${ZSH_FILE}.zwc"; exit "$rc"
